# 数组排序

In [2]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


## sort 函数

先看这个例子：

In [4]:
names = array(['bob', 'sue', 'jan', 'ad'])
weights = array([20.8, 93.2, 53.4, 61.8])

sort(weights)

array([ 20.8,  53.4,  61.8,  93.2])

`sort` 返回的结果是从小到大排列的。

## argsort 函数

`argsort` 返回从小到大的排列在数组中的索引位置：

In [5]:
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int64)

可以用它来进行索引：

In [6]:
weights[ordered_indices]

array([ 20.8,  53.4,  61.8,  93.2])

In [7]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'], 
      dtype='|S3')

使用函数并不会改变原来数组的值：

In [10]:
weights

array([ 20.8,  93.2,  53.4,  61.8])

## sort 和 argsort 方法

数组也支持方法操作：

In [11]:
data = array([20.8,  93.2,  53.4,  61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int64)

`argsort` 方法与 `argsort` 函数的使用没什么区别，也不会改变数组的值。

In [12]:
data

array([ 20.8,  93.2,  53.4,  61.8])

但是 `sort`方法会改变数组的值：

In [13]:
data.sort()

In [14]:
data

array([ 20.8,  53.4,  61.8,  93.2])

## 二维数组排序

对于多维数组，sort方法默认沿着最后一维开始排序：

In [18]:
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[ 0.2,  0.1,  0.5],
       [ 0.4,  0.8,  0.3],
       [ 0.9,  0.6,  0.7]])

对于二维数组，默认相当于对每一行进行排序：

In [19]:
sort(a)

array([[ 0.1,  0.2,  0.5],
       [ 0.3,  0.4,  0.8],
       [ 0.6,  0.7,  0.9]])

改变轴，对每一列进行排序：

In [20]:
sort(a, axis = 0)

array([[ 0.2,  0.1,  0.3],
       [ 0.4,  0.6,  0.5],
       [ 0.9,  0.8,  0.7]])

## searchsorted 函数

    searchsorted(sorted_array, values)

`searchsorted` 接受两个数组，其中，第一个必需是已排序的数组。

In [21]:
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])

In [22]:
searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int64)

排序数组：

|0|1|2|3|4|
|-|-|-|-|-|
|0.0|0.25|0.5|0.75|1.0

数值数组：

|-|-|-|-|-|-
|0.1|0.8|0.3|0.12|0.5|0.25|

`searchsorted` 返回的值相当于将第二个数组中的值插入第一个数组中的位置：