# 通用函数

**Numpy** 有两种基本对象：`ndarray (N-dimensional array object)` 和 `ufunc (universal function object)`。`ndarray` 是存储单一数据类型的多维数组，而 `ufunc` 则是能够对数组进行处理的函数。

例如，我们之前所接触到的二元操作符对应的 **Numpy** 函数，如 `add`，就是一种 `ufunc` 对象，它可以作用于数组的每个元素。

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
b = np.array([2,3,4])

np.add(a, b)

array([2, 4, 6])

因为 `add` 是一种对象，所以相应的它还支持一些方法：

In [3]:
np.add.reduce(a, axis=0)

3

In [4]:
np.add.accumulate(a, axis=0)

array([0, 1, 3])

In [5]:
np.add.outer(a, b)

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

`ufunc` 对象支持以下方法：

## reduce 方法

    op.reduce(a)

将`op`沿着某个轴应用，使得数组 `a` 的维数降低一维。

add 作用到一维数组上相当于求和：

$$
\begin{align}
y & = add.recuce(a) \\
& = a[0] + a[1] + ... + a[N-1] \\
& = \sum_{n=0}^{N-1} a[n]
\end{align}
$$

In [6]:
a = np.array([1,2,3,4])

np.add.reduce(a)

10

多维数组默认只按照第一维进行运算：

In [7]:
a = np.array([[1,2,3],[4,5,6]])

np.add.reduce(a)

array([5, 7, 9])

指定维度：

In [8]:
np.add.reduce(a, 1)

array([ 6, 15])

作用于字符串：

In [9]:
a = np.array(['ab', 'cd', 'ef'], np.object)

np.add.reduce(a)

'abcdef'

逻辑运算：

In [10]:
a = np.array([1,1,0,1])

np.logical_and.reduce(a)

False

In [11]:
np.logical_or.reduce(a)

True

## accumulate 方法

    op.accumulate(a)

`accumulate` 可以看成保存 `reduce` 每一步的结果所形成的数组。

$$
\begin{align}
y & = add.accumulate(a) \\
& = \left[\sum_{n=0}^{0} a[n], \sum_{n=0}^{1} a[n], ..., \sum_{n=0}^{N-1} a[n]\right]
\end{align}
$$

与之前类似：

In [12]:
a = np.array([1,2,3,4])

np.add.accumulate(a)

array([ 1,  3,  6, 10])

In [13]:
a = np.array(['ab', 'cd', 'ef'], np.object)

np.add.accumulate(a)

array(['ab', 'abcd', 'abcdef'], dtype=object)

In [14]:
a = np.array([1,1,0,1])

np.logical_and.accumulate(a)

array([ True,  True, False, False], dtype=bool)

In [15]:
np.logical_or.accumulate(a)

array([ True,  True,  True,  True], dtype=bool)

## reduceat 方法